### ISSUE TITLE
Não consigo dar o import

### ISSUE THREAD

**Issue by amsilvestre** [leogregianin/viacep-python#1]
Não consigo dar o import viacep.
Usando o Anaconda.

**Comment by leogregianin** [comment]
Olá @amsilvestre, nunca utilizei ele no Jupyter somente em projetos pythons nativos.

Vou testar com o Anaconda e te dou um feedback ou se quiser corrigir o que encontrou de inconsistência também pode ficar a vontade para fazer um pull request.

Até mais.

**Comment by leogregianin** [comment]
Adicionei ao repositório um exemplo com Anaconda. 
Talvez o local da instalação do pacote entre as versões nativas do python e a versão do Anaconda esteja com diferenças no seu ambiente.

**Comment by leogregianin** [comment]
Vou fechar essa issue, se tiver mais alguma dificuldade pode reabrí-la.
